export const OPTIONS = [
  {
    category: "Gender",
    list: ["Male", "Female", "Non-Binary", "Gender Queer"],
  },
  {
    category: "Pronouns",
    list: ["He/Him", "She/Her", "They/Them"],
  },
  {
    category: "Specialization",
    list: [
      "ADHD",
      "Abuse",
      "Addiction",
      "Alcohol use",
      "Amyotrophic Lateral Sclerosis (ALS)",
      "Anger/Anger Management",
      "Anti-Oppression Grief",
      "Anxiety",
      "Attachment Disorder",
      "BIPOC",
      "Behavioural Issues",
      "Bipolar Disorder",
      "Body Image Challenges",
      "Borderline personality Disorder",
      "Boundaries",
      "Burnout",
      "Career Development or Direction",
      "Career Issues",
      "Child",
      "Childhood Trauma",
      "Childhood Abuse/Neglect",
      "Chronic Pain",
      "Codependency",
      "Couples",
      "Cultural Transitions",
      "Custom Group Workshops For Organizations",
      "Depression",
      "Developing Positive Habits",
      "Developmental Disorders",
      "Dissociative identity disorder (DID)",
      "Domestic Violence",
      "Drug Abuse",
      "Eating Disorders",
      "Emotional Disturbance",
      "Empowerment",
      "Existential Concern/Life Crises",
      "Family Conflict",
      "Fatigue",
      "Goal Attainment",
      "Grief/Loss",
      "Health",
      "Homesickness",
      "Identity Issues",
      "Immigrant Experiences",
      "Impulse Control Disorders",
      "Infidelity",
      "Intergenerational Trauma",
      "Italian Community",
      "LGBTQIA+",
      "Learning Disabilities",
      "Life Coaching",
      "Life Transitions",
      "Low Motivation",
      "Marginalization",
      "Marital and Premarital",
      "Men’s Issues",
      "Mood Disorders",
      "Multicultural Counselling",
      "Neurodivergence",
      "Obsessive-Compulsive (OCD)",
      "Obsessive-Compulsive Disorder (OCD)",
      "Oppositional Defiance",
      "Oppression",
      "Panic disorder",
      "Parent - Child Relationship",
      "Parenting",
      "Peer Relationships",
      "Perfectionism",
      "Personality Disorders",
      "Pregnant and/or Postpartum Parents",
      "Racial Identity",
      "Relationship Issues",
      "Relationships",
      "Self Esteem",
      "Self-Harming",
      "Self-Criticism",
      "Sexual Abuse",
      "Sexuality",
      "Spirituality",
      "Stress Management/Stress",
      "Substance Use",
      "Suicidal Ideation",
      "Teen Violence",
      "Trauma and PTSD",
      "Women’s Issues",
    ],
  },

  {
    category: "Approach",
    list: [
      "Accelerated Experiential-dynamic Psychotherapy",
      "Acceptance and Commitment (ACT)",
      "AEDP",
      "Applied Behavioural Analysis",
      "Art Therapy",
      "Attachment-Based",
      "Clinical Supervision and Licensed Supervisors",
      "Cognitive Behavioural Therapy",
      "Compassion Focused",
      "Culturally Goultsensitive",
      "Dialectical Behavioral Therapy",
      "Eclectic",
      "Eclectic (Trauma-Informed)",
      "EMDR",
      "Emotionally Focused",
      "Energy Psychology",
      "Equine and Animal-Assisted Therapies",
      "Evidence Based",
      "Existentialism",
      "Experiential Therapy",
      "Expressive Arts",
      "Family Systems",
      "Family Systems Therapy",
      "Feminist Therapy",
      "Focusing",
      "Focusing-Oriented Therapy",
      "Gestalt",
      "Holistic Psychology",
      "Humanistic",
      "Imago",
      "Integrative",
      "Internal Family Systems (IFS)",
      "Interpersonal",
      "Intervention",
      "Life Coach/Coaching",
      "Mindfulness-based (MBCT)",
      "Motivational Interviewing",
      "Multi-Dimensional",
      "Multicultural",
      "Narrative Therapy",
      "Nature Therapy",
      "Parent-Child Interaction (PCIT) S-Focusedplay",
      "Person-Centered",
      "Play Therapy",
      "Positive Psychology",
      "Reality Therapy",
      "Schema Therapy",
      "Self-Compassion",
      "Self Relational Theory and Therapy",
      "Sensorimotor Psychotherapy (SP)",
      "Solution-Focused Therapy",
      "Somatic",
      "Strength-Based",
      "Systemic Therapy",
      "Trauma-Focused",
      "Trauma-Focused Compassionate Inquiry",
    ],
  },
  {
    category: "Credentials",
    list: ["CCC", "CCP", "RCC", "RSW", "PhD"],
  },
  {
    category: "Age",
    list: [
      "Toddlers/Preschoolers (0 to 6)",
      "Children (6 to 10)",
      "Preteens/Tweens (11 to 13)",
      "Adolescents/Teenagers (14 to 19)",
      "Adults",
      "Elders (65+)",
    ],
  },
  {
    category: "Ethnicity",
    list: [
      "Asian",
      "Indigenous",
      "Hispanic and Latino",
      "Black",
      "Hawaiian",
      "Guatemalan",
    ],
  },
  {
    category: "Roles",
    list: [
      "Counselor",
      "Supervisor",
    ],
  },
  {
    category: "Provinces",
    list: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Northwest Territories",
      "Nova Scotia",
      "Nunavut",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon"
    ],
  },
  {
    category: "DNE",
    list: [
      "Select A Province"
    ],
  },
];
//These are lower case with _ because it will be like this is the form data in AddCounselor
export const PROVINCE_CODE_MAP = {
  'alberta': 'AB',
  'british_columbia': 'BC',
  'manitoba': 'MB',
  'new_brunswick': 'NB',
  'newfoundland_and_labrador': 'NL',
  'northwest_territories': 'NT',
  'nova_scotia': 'NS',
  'nunavut': 'NU',
  'ontario': 'ON',
  'prince_edward_island': 'PE',
  'quebec': 'QC',
  'saskatchewan': 'SK',
  'yukon':'YT'
};