export const FILTERS = [
  {
    category: "Issues",
    list: [
      "ADHD",
      "Addiction",
      "Adoption",
      "Alcohol Use",
      "Alzheimer's",
      "Anger Management",
      "Anxiety",
      "Bipolar Disorder",
      "Domestic Abuse",
      "Obesity",
      "PTSD",
    ],
  },
  {
    category: "Insurance",
    list: [
      "Aetna",
      "Allegiance",
      "Alliance",
      "Behavioral Health Systems",
      "Blue Care Network",
      "Blue Cross",
      "Blue Shield",
      "Ceridian",
      "Cigna",
      "ComPsych",
      "Great-West Life",
    ],
  },
  { category: "Gender", list: ["Male", "Female"] },
  {
    category: "Therapy Type",
    list: [
      "Cognitive Behavioural (CBT)",
      "Trauma Focused",
      "Attachment-Based",
      "Somatic",
      "Dialectical",
      "Acceptance and Commitment (ACT)",
      "Psychodynamic",
      "EMDR",
      "Strength-Based",
      "Culturally Sensitive",
    ],
  },
  {
    category: "Age",
    list: [
      "Toddlers/Preschoolers (0 to 6)",
      "Children (6 to 10)",
      "Preteens/Tweens (11 to 13)",
      "Adolescents/Teenagers (14 to 19)",
      "Adults",
      "Elders (65+)",
    ],
  },
  {
    category: "Ethnicity",
    list: [
      "Asian",
      "Indigenous",
      "Hispanic and Latino",
      "Black",
      "Hawaiian",
      "Guatemalan",
    ],
  },
];
