export const FILTERS = [
  {
    category: "Issues",
    list: [
      "ADHD",
      "Abuse",
      "Addiction",
      "Alcohol use",
      "Amyotrophic Lateral Sclerosis (ALS)",
      "Anger/Anger Management",
      "Anti-Oppression Grief",
      "Anxiety",
      "Attachment Disorder",
      "BIPOC",
      "Behavioural Issues",
      "Behavioural issues",
      "Bipolar Disorder",
      "Body Image Challenges",
      "Borderline personality disorder",
      "Boundaries",
      "Burnout",
      "Career Development or Direction",
      "Career issues",
      "Child",
      "Childhood Trauma",
      "Childhood abuse/neglect",
      "Chronic Pain",
      "Codependency",
      "Couples",
      "Cultural Transitions",
      "Custom Group Workshops For Organizations",
      "Depression",
      "Developing Positive Habits",
      "Developmental Disorders",
      "Domestic Violence",
      "Drug Abuse",
      "Eating Disorders",
      "Emotional Disturbance",
      "Empowerment",
      "Existential concern/Life crises",
      "Family Conflict",
      "Fatigue",
      "Goal Attainment",
      "Grief/loss",
      "Health",
      "Homesickness",
      "Identity issues",
      "Immigrant experiences",
      "Impulse Control Disorders",
      "Infidelity",
      "Intergenerational trauma",
      "Italian community",
      "LGBTQIA+",
      "Learning disabilities",
      "Life Coaching",
      "Life Transitions",
      "Low Motivation",
      "Marginalization",
      "Marital and Premarital",
      "Men’s issues",
      "Mood Disorders",
      "Multicultural Counselling",
      "Neurodivergence",
      "Obsessive-Compulsive (OCD)",
      "Obsessive-Compulsive Disorder (OCD)",
      "Oppositional Defiance",
      "Oppression",
      "Panic disorder",
      "Parent - Child Relationship",
      "Parenting",
      "Peer Relationships",
      "Perfectionism",
      "Personality Disorders",
      "Pregnant and/or postpartum parents",
      "Racial Identity",
      "Relationship Issues",
      "Relationships",
      "Self Esteem",
      "Self-Harming",
      "Self-criticism",
      "Sexual Abuse",
      "Sexuality",
      "Spirituality",
      "Stress Management/Stress",
      "Substance Use",
      "Suicidal ideation",
      "Teen Violence",
      "Trauma and PTSD",
      "Women’s issues",
    ],
  },
  {
    category: "Insurance",
    list: [
      "Aetna",
      "Allegiance",
      "Alliance",
      "Behavioral Health Systems",
      "Blue Care Network",
      "Blue Cross",
      "Blue Shield",
      "Ceridian",
      "Cigna",
      "ComPsych",
      "Great-West Life",
    ],
  },
  { category: "Gender", list: ["Male", "Female"] },
  {
    category: "Therapy Type",
    list: [
      "Cognitive Behavioural (CBT)",
      "Trauma Focused",
      "Attachment-Based",
      "Somatic",
      "Dialectical",
      "Acceptance and Commitment (ACT)",
      "Psychodynamic",
      "EMDR",
      "Strength-Based",
      "Culturally Sensitive",
    ],
  },
  {
    category: "Age",
    list: [
      "Toddlers/Preschoolers (0 to 6)",
      "Children (6 to 10)",
      "Preteens/Tweens (11 to 13)",
      "Adolescents/Teenagers (14 to 19)",
      "Adults",
      "Elders (65+)",
    ],
  },
  {
    category: "Ethnicity",
    list: [
      "Asian",
      "Indigenous",
      "Hispanic and Latino",
      "Black",
      "Hawaiian",
      "Guatemalan",
    ],
  },
];
